Update README.md to include providers information
I was getting the following error:

NullInjectorError: No provider for InjectionToken angularfire2.app.options!

Which was resolved by simply adding the FIREBASE_OPTIONS into the provider. Ref https://stackoverflow.com/questions/71431785/angular-fire-no-provider-for-injectiontoken-angularfire2-app-options