Update 1 - Install and Setup.md
 'moduleId: module.id' is causing errors 
"url_resolver.js:248Uncaught TypeError: uri.match is not a function_split @ 
url_resolver.js:248getUrlScheme @ url_resolver.js:91componentModuleUrl @ ".

Removed it from docs as the default angular-app does not contains an entry.  I need to learn to consolidate small changes.